env:
  global:
    - CXX=g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then brew install rethinkdb  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then rethinkdb --daemon ; fi


addons:
  rethinkdb: '2.3'

# Do not insert any code under here without making sures it's in publishingtest first
language: node_js

plugins:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "stable"
  - "6.9.5"

matrix:
  include:
    - node_js: "6.9.5"
      os: osx

script:
  - npm run test
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/package.sh
  - chmod 555 package.sh
  - ./package.sh

deploy:
  - provider: s3
    access_key_id:
      secure: "GhcFfip61RL+PuuDKNvNpb1ChNBwU56V6uJp805lDrtnKKmA9QaymCi0BmagtrfODdseoPEyxEJ8W6wRasiNlZXVmE0ZMnuL6MUY6/FIICrHYbLN0HBfaAxAL/9BashlDeDmFSndOKWgl3FNCAjkiSLx2X07BCcdLdt4mclY/44="
    secret_access_key:
      secure: "ontwWXsfar5lyYZEioMlWNg8ZWXwYO0vb4Tz38N/AHLIPKYiyWZaumYG6bzm73oYHk0uhCorJchVkhQKBN2afRmA6iVNwurE0x9G48sFCzB54XwXlfprJYxVskubhlumTLgtUbgiI/2DfeW/k4L1rWgZpzjMC0cjHYJ8Jvuz1cM="
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "mBuYDIf2KhKoBb4dfIM0p6H8pkQy2qqY2PGcn45AW94YVosHmyOz7nye/h2rgVYOhoM77RYBQNtKbMARfm7CwOMtgdYHr8WYIt0pqjY3ceEjm/2hUOoit9jx+6iOSTwA+1RVAPmpF0T2zQLTTLbkYpeRJCxq4qiyf+2WWuS7e2E="
    file_glob: true
    file:
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/test.sh
  - chmod 555 test.sh
  - ./test.sh

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
