os:
  - Visual Studio 2015

platform:
  - x64

install:
  - ps: Install-Product node 6.9.5
  - npm install
  - curl -L https://download.rethinkdb.com/windows/rethinkdb-2.3.5.zip > rethinkdb.zip
  - unzip rethinkdb.zip -d rethinkdb
  - ps: $MyProcess = Start-Process rethinkdb/rethinkdb.exe -PassThru

on_finish:
  - ps: Stop-Process -Id $MyProcess.Id

test_script:
  - node --version
  - npm --version
  - npm test
  - curl -o package.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/package.sh
  - bash package.sh
  - For /d %%d in ( build\** ) do MOVE %%d %cd%


# Do not insert any code under here without making sures it's in publishingtest first

artifacts:
  - path: 'build\*.zip'
    name: 'deepstream.io-connector'

  - path: '**\*.zip'

deploy:
  - provider: S3
    access_key_id:
      secure: zIKwOEzh56IXWlpXWMDwjC9Dqz58ZifBBQUZ43wDQWs=
    secret_access_key:
      secure: br3dL6aFlkMBeqdXSeXfKeZmjyZl1OGD9STaUiGXsWic50DEqedx24C0LipYJqYI
    bucket: ds-server-artifacts
    folder: $(APPVEYOR_REPO_NAME)
    on:
      appveyor_repo_tag: false

  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token:
      secure: tZHuiZVCwkXRYMihVyoNrmDxAm6xPbXyop7Plg5uUWIIqA1EoUCrTYd/V+0D1I+Y
    artifact: 'deepstream.io-connector'
    draft: false
    on:
      appveyor_repo_tag: true

after_deploy:
  - curl -o test.sh -L https://raw.githubusercontent.com/deepstreamIO/deepstream.io-connector-publishingtest/master/scripts/test.sh
  - chmod 555 test.sh
  - bash test.sh

build: off
